# Generated by Django 2.1.3 on 2018-11-26 17:49

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bowler',
            fields=[
                ('bowler_id', models.AutoField(primary_key=True, serialize=False)),
                ('bowler_name', models.TextField()),
                ('bowler_email', models.EmailField(max_length=128)),
                ('bowler_phone', models.CharField(max_length=10)),
                ('bowler_address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('avg_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BowlerMatchStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_1_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('game_2_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('game_3_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('match_average', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bowler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BowlingApp.Bowler')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('league_email', models.EmailField(max_length=128)),
                ('league_name', models.CharField(max_length=120)),
                ('league_venue', models.TextField()),
                ('city', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('league', models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_1_game_1_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('team_1_game_2_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('team_1_game_3_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('team_1_total_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(900)])),
                ('team_2_game_1_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('team_2_game_2_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('team_2_game_3_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('team_2_total_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(900)])),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('ref_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_email', models.EmailField(max_length=128)),
                ('password', models.CharField(max_length=8)),
                ('ref_name', models.CharField(max_length=120)),
                ('ref_phone', models.CharField(max_length=10)),
                ('ref_address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_email', models.EmailField(max_length=128)),
                ('team_name', models.TextField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tm_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_1', to='BowlingApp.Bowler')),
                ('tm_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_2', to='BowlingApp.Bowler')),
                ('tm_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_3', to='BowlingApp.Bowler')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BowlingApp.Team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='match_winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='BowlingApp.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BowlingApp.Referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='BowlingApp.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='BowlingApp.Team'),
        ),
        migrations.AddField(
            model_name='bowlermatchstats',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BowlingApp.Match'),
        ),
        migrations.AddField(
            model_name='bowlermatchstats',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BowlingApp.Team'),
        ),
    ]
