# Generated by Django 2.1.3 on 2018-11-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BowlingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='league',
        ),
    ]
