# Generated by Django 2.1.3 on 2018-12-02 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BowlingApp', '0002_remove_league_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='ref_id',
        ),
        migrations.AlterField(
            model_name='match',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to=settings.AUTH_USER_MODEL),
        ),
    ]
