# Generated by Django 2.1.3 on 2018-12-03 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BowlingApp', '0003_auto_20181202_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowler',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bowlermatchstats',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bowlermatchstats',
            name='bowler_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='tm_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='tm_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='tm_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_3', to=settings.AUTH_USER_MODEL),
        ),
    ]
