# Generated by Django 2.1.3 on 2018-12-04 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BowlingApp', '0009_auto_20181203_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowler',
            name='avg_score',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
