# Generated by Django 2.1.3 on 2018-12-04 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BowlingApp', '0010_auto_20181203_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_avg',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
