# Generated by Django 2.1.3 on 2018-12-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BowlingApp', '0012_team_captain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstats',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='team_id',
        ),
        migrations.DeleteModel(
            name='TeamStats',
        ),
    ]
