# Generated by Django 2.1.3 on 2018-12-04 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BowlingApp', '0013_auto_20181203_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.AddField(
            model_name='match',
            name='ref',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reftomatch', to='BowlingApp.Referee'),
            preserve_default=False,
        ),
    ]
