# Generated by Django 2.1.3 on 2018-12-04 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BowlingApp', '0015_auto_20181203_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='reffie',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reffie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captain', to=settings.AUTH_USER_MODEL),
        ),
    ]
