# Generated by Django 2.1.3 on 2018-12-04 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BowlingApp', '0016_auto_20181203_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='reffie',
        ),
    ]
