# Generated by Django 2.1.3 on 2018-12-06 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BowlingApp', '0018_remove_team_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1_game_1_score',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(900)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_1_game_2_score',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(900)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_1_game_3_score',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(900)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_1_total_score',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2700)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_game_1_score',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(900)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_game_2_score',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(900)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_game_3_score',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(900)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_total_score',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2700)]),
        ),
    ]
